function [ CropInt,Result, Error] = FitDSigmoid3(days, crop, CropName)
%CREATEFIT1(DAYS,PAMUK)
%  Create a fit.
%
%  Data for 'dsigmoid' fit:
%      X Input : days
%      Y Output: pamuk
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Oct-2015 07:44:10


%% Fit: 'dsigmoid'.
% crop = sgolayfilt(crop(:),3,5);
[xData, yData] = prepareCurveData( days(:), crop(:) );

% Set up fittype and options.
ft = fittype( 'a + 0.5*b*( tanh(p*(x-d1)) + tanh(q*(x-d2)) )', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.DiffMaxChange = 0.001;
% opts.Display = 'Off';

opts.MaxFunEvals = 10000;
opts.MaxIter = 10000;
opts.Robust = 'Bisquare';



opts.Lower = [0.1 0.1 -50 100 0.0 -0.2];
opts.StartPoint = [0.2 0.6 150 180 0.05 -0.05];
opts.Upper = [1 1 220 300 0.2 0];

% opts.Lower = [0.1 0.1 150 225 0.0 -0.1];
% opts.StartPoint = [0.2 0.6 180 250 0.05 -0.05];
% opts.Upper = [1 1 300 365 0.1 0];


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


f = fitresult;
% [f.a f.b f.d1 f.d2 f.p f.q ]
D(1) = -1./f.p+f.d1; %D1
D(2)  = 1./f.p+f.d1; %D2
D(3) = 1./f.q+f.d2; %D3
D(4)  = -1./f.q+f.d2; %D4
D(D == -Inf ) = 0;
D(D == Inf ) = 0;

Result = [f.a f.b f.d1 f.d2 f.p f.q D];
% x = 116:302;
x = 1:365;
CropInt = f.a + 0.5*f.b*( tanh(f.p*(x-f.d1)) + tanh(f.q*(x-f.d2)));
x = days;
CropInt2 = f.a + 0.5*f.b*( tanh(f.p*(x-f.d1)) + tanh(f.q*(x-f.d2)));
Error = max(abs(crop(:) - CropInt2(:)));
%
if(gof.rsquare < 0.8 ||fitresult.d1  ~= 0)
% Plot fit with data.
    figure( 'Name', 'dsigmoid' );
    h = plot( fitresult, xData, yData );
    legend( h, 'Ölçümler', 'Fenoloji', 'Location', 'NorthEast' );
    % Label axes
    xlabel ('Yýlýn Günü')
    ylabel ('NDVI')
    title (CropName)
    xlim([1 365]);
    ylim([0 1]);
    grid on
    waithere = 0;
end


