CropNames{999} = 'Unknown';
%% 
% CropNames{32} = 'Wheat';
% CropNames{192} = 'Alfalfa';
% CropNames{128} = 'Sainfoin';
% CropNames{222} = 'Fallow';
%%
CropNames{1} = 'BUGDAY'; %'Buðday';%
% CropNames{1} = 'Buðday';%
CropNames{2} = 'Buðday Makarnalýk';
% CropNames{3} = 'Arpa4Food';
CropNames{4} = 'ARPA';
% CropNames{5} = 'Havuç';
CropNames{6} = 'Yulaf';
% CropNames{7} = 'Yulaf4Food';
CropNames{8} = 'Corn';%';%Dane
% CropNames{8} = 'Buðday ve Mýsýr';%';%Dane
% CropNames{8} = 'Mýsýr';%';%Dane
CropNames{9} = 'MISIR ';%Muhtelif
CropNames{10} = 'BUGDAY / MISIR 2';%sýlajlýk
CropNames{11} = 'Fýstýk';
CropNames{13} = 'Arpa ve Mýsýr 2';
CropNames{12} = 'Çeltik';
% CropNames{16} = 'Tritikale';
CropNames{20} = 'Chickpea'; %'NOHUT';
CropNames{22} = 'MERCIMEK';
% CropNames{23} = 'Kýrmýzý Mercimek';
CropNames{25} = 'Fið';
CropNames{30} = 'Þeker Pancarý';
CropNames{31} = 'Canola';
CropNames{33} = 'Haþhaþ';
CropNames{34} = 'Cotton';%Cotton';
% CropNames{34} = 'Pamuk';
CropNames{35} = 'Buðday-Pamuk'; %'Wheat-Cotton2';%Cotton';
CropNames{41} = 'Sunflower';
CropNames{44} = 'Soybean';
CropNames{47} = 'Patates';
% CropNames{50} = 'Yonca Tohumu';
CropNames{51} = 'Alfalfa';% 'Yonca';
CropNames{52} = 'Fið';
CropNames{54} = 'Lahana';
CropNames{55} = 'Marul';
CropNames{75} = 'Bezelye';
CropNames{80} = 'Kavun';
CropNames{81} = 'Karpuz';
CropNames{84} = 'Kabak';
CropNames{90} = 'Acý Biber';
CropNames{91} = 'Biber';
CropNames{93} = 'Sarýmsak';
CropNames{95} = 'Soðan';
CropNames{99} = 'Other';
CropNames{108} = 'Elma';
CropNames{114} = 'Erik';
CropNames{116} = 'Kayýsý';
CropNames{118} = 'Kiraz';
% CropNames{119} = 'Mandalina';
% CropNames{120} = 'Mandalina (SDLS)';
% CropNames{121} = 'Þeftali';
% CropNames{122} = 'Portakal';
% CropNames{123} = 'Greyfurt';
CropNames{124} = 'Ceviz';
CropNames{125} = 'Badem';
CropNames{133} = 'Nar';
CropNames{135} = 'Üzüm(Çekirdeksiz)';
% CropNames{137} = 'Üzüm(Kurutmalýk)';
% CropNames{139} = 'Üzüm(Þaraplýk)';
CropNames{145} = 'Zeytin';
CropNames{149} = 'Mera';
CropNames{151} = 'Nadas';
% CropNames{161} = 'Limon';
CropNames{177} = 'Nane';
CropNames{181} = 'OT';
CropNames{190} = 'Antep F.';
% CropNames{186} = 'Gül';
% CropNames{201} = 'Turp';
% CropNames{212} = 'Fasülye(Kurutmalýk)';
CropNames{210} = 'Domates';
% CropNames{215} = 'Domates (Salçalýk)';
CropNames{222} = 'Sebze Bahçesi';
CropNames{225} = 'Fasülye (Taze)';
% CropNames{235} = 'SorghumMilo';
% CropNames{237} = 'Sudangrass';
% CropNames{245} = 'Tangelo';
% CropNames{249} = 'Urun1';
% CropNames{255} = 'Urun2';
CropNames{302} = 'Zeytin';
CropNames{333} = 'Other';
ProductNames = CropNames;